# ~~~~~~~~~~~~~~~~~~~~~~
# Circles Staging Values
# ~~~~~~~~~~~~~~~~~~~~~~
# Main host
host: staging.circles.garden

# circles-api Service
# ~~~~~~~~~~~~~~~~~~~
apiService:
  # Docker image tag
  imageTag: v1.12.0

  # Ingress
  host: api.staging.circles.garden

  # Timeout in ms
  transferStepsTimeout: 150000

  # worker
  worker:
    enabled: true

# circles-payment-api Service
# ~~~~~~~~~~~~~~~~~~~

apiPaymentService:
  enabled: true
  # Docker image tag
  imageTag: v1.1.0

  # Ingress
  host: payment.staging.circles.garden

  # chain id
  chaindID: 10200
  corsRegex: https://relayer.staging.circles.garden
  fastifyLogs: info
# circles-relayer Service
# ~~~~~~~~~~~~~~~~~~~~~~~
relayerService:
  # Docker image tag
  imageTag: v5.0.4-1-gb85b7b4

  # Ingress
  host: relay.staging.circles.garden

  # Minimum trust connections needed to fund the Safe deployment
  minTrustConnections: 1

# AWS S3 Configuration
# ~~~~~~~~~~~~~~~~~~~~
aws:
  # Bucket for user content storage (via api)
  bucketUserContent: circles-garden-profile-pictures

  # Bucket for trust edges file storage (via api-worker)
  bucketTrustNetwork: circles-ubi-network-staging

# "The Graph" Configuration
# ~~~~~~~~~~~~~~~~~~~~~~~~~
graph:
  # Graph node URL
  endpoint: https://graph.infra.circles.garden

  # Circles subgraph name
  subgraph: circlesubi/circles-ubi-stg

# Smart Contract Addresses taken from https://github.com/safe-global/safe-deployments/issues/157
# Smart Contract Addresses
# ~~~~~~~~~~~~~~~~~~~~~~~~
contracts:
  hubAddress: 0xdbF22D4e8962Db3b2F1d9Ff55be728A887e47710
  proxyFactoryAddressCRC: 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2
  safeAddressCRC: 0x3E5c63644E683549055b9Be8653de26E0B4CD36E
  proxyFactoryAddress: 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2
  safeAddress130: 0x3E5c63644E683549055b9Be8653de26E0B4CD36E
  safeAddress: 0x3E5c63644E683549055b9Be8653de26E0B4CD36E
  fallBackAddress: 0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4
  multiSendAddress: 0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761
  multiSendCallOnlyAddress: 0x40A2aCCbd92BCA938b02010E17A5b8929b49130D

# Relayer Addresses
# ~~~~~~~~~~~~~~~~~
relayer:
  funderAddress: 0x66c0FE88C2Aef9DE75CB725E8bCCE61891DF4393
  senderAddress: 0xB573eBb6A0b10A951a2a7305F4746cc9D7EBb785

# Pathfinder config
# ~~~~~~~~~~~~~~~~~
pathfinder:
  endpoint: https://pathfinder.testing.circles.garden
