# ~~~~~~~~~~~~~~~~~~~~~~
# Circles Staging Values
# ~~~~~~~~~~~~~~~~~~~~~~
# Main host
host: staging.circles.garden

# circles-api Service
# ~~~~~~~~~~~~~~~~~~~
apiService:
  # Docker image tag
  imageTag: v1.9.1

  # Ingress
  host: api.staging.circles.garden

  # Timeout in ms
  transferStepsTimeout: 150000
  
  # worker 
  worker:
    enabled: true 
# circles-relayer Service
# ~~~~~~~~~~~~~~~~~~~~~~~
relayerService:
  # Docker image tag
  imageTag: v5.0.3-2-g910a7f1

  # Ingress
  host: relay.staging.circles.garden

# AWS S3 Configuration
# ~~~~~~~~~~~~~~~~~~~~
aws:
  # Bucket for user content storage (via api)
  bucketUserContent: circles-ubi-staging

  # Bucket for trust edges file storage (via api-worker)
  bucketTrustNetwork: circles-ubi-network-staging

# "The Graph" Configuration
# ~~~~~~~~~~~~~~~~~~~~~~~~~
graph:
  # Graph node URL
  endpoint: https://graph.testing.circles.garden

  # Circles subgraph name
  subgraph: circlesubi/circles-ubi-stg

# Smart Contract Addresses taken from https://github.com/safe-global/safe-deployments/issues/157
# Smart Contract Addresses
# ~~~~~~~~~~~~~~~~~~~~~~~~
contracts:
  hubAddress: 0xdbF22D4e8962Db3b2F1d9Ff55be728A887e47710
  proxyFactoryAddressCRC: 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2
  safeAddressCRC: 0x3E5c63644E683549055b9Be8653de26E0B4CD36E
  proxyFactoryAddress: 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2
  safeAddress130: 0x3E5c63644E683549055b9Be8653de26E0B4CD36E 
  safeAddress: 0x3E5c63644E683549055b9Be8653de26E0B4CD36E
  fallBackAddress: 0x1AC114C2099aFAf5261731655Dc6c306bFcd4Dbd

# Relayer Addresses
# ~~~~~~~~~~~~~~~~~
relayer:
  funderAddress: 0x66c0FE88C2Aef9DE75CB725E8bCCE61891DF4393
  senderAddress: 0xB573eBb6A0b10A951a2a7305F4746cc9D7EBb785

# Pathfinder config
# ~~~~~~~~~~~~~~~~~
pathfinder:
  endpoint: https://pathfinder.testing.circles.garden
