# ~~~~~~~~~~~~~~~~~~~~~~~~~
# Circles Production Values
# ~~~~~~~~~~~~~~~~~~~~~~~~~
# Main host
host: circles.garden

# circles-api Service
# ~~~~~~~~~~~~~~~~~~~
apiService:
  # Docker image tag
  imageTag: v1.10.0

  # Ingress
  host: api.circles.garden

  # Worker
  worker:
    enabled: false
# circles-relayer Service
# ~~~~~~~~~~~~~~~~~~~~~~~
relayerService:
  # Docker image tag
  imageTag: v5.0.4-1-gb85b7b4
  # Ingress
  host: relay.circles.garden

# circles-payment-api Service
# ~~~~~~~~~~~~~~~~~~~

apiPaymentService:
  enabled: false
 # Ingress
  host: payment.circles.garden

  # chain id
  chaindID: 100

  corsRegex: http[s]?:\/\/.*\.circles\.garden.*
  fastifyLogs: info
# AWS S3 Configuration
# ~~~~~~~~~~~~~~~~~~~~
aws:
  # Bucket for user content storage (via api)
  bucketUserContent: circles-ubi

  # Bucket for trust edges file storage (via api-worker)
  bucketTrustNetwork: circles-ubi-network

# "The Graph" Configuration
# ~~~~~~~~~~~~~~~~~~~~~~~~~
graph:
  # Graph node URL
  endpoint: https://graph.infra.circles.garden
  # Circles subgraph name
  subgraph: circlesubi/circles-ubi

# Smart Contract Addresses
# ~~~~~~~~~~~~~~~~~~~~~~~~
contracts:
  hubAddress: 0x29b9a7fBb8995b2423a71cC17cf9810798F6C543
  safeAddressCRC: 0x2CB0ebc503dE87CFD8f0eCEED8197bF7850184ae
  safeAddress130: 0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552
  proxyFactoryAddressCRC: 0x8b4404DE0CaECE4b966a9959f134f0eFDa636156
  proxyFactoryAddress: 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2
  safeAddress: 0x3E5c63644E683549055b9Be8653de26E0B4CD36E
  fallBackAddress: 0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4
  multiSendAddress: 0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761
  multiSendCallOnlyAddress: 0x40A2aCCbd92BCA938b02010E17A5b8929b49130D

# Relayer Addresses
# ~~~~~~~~~~~~~~~~~
relayer:
  funderAddress: 0x450Fc3eAc8b847a759Cb05790cE7A1f465ac0cE8
  senderAddress: 0x9944Ce8e27CE1f16C4003f108b1C09e5Ae011bA0

# Pathfinder config
# ~~~~~~~~~~~~~~~~~
pathfinder:
  endpoint: https://pathfinder.circlesubi.id
