# ~~~~~~~~~~~~~~~~~~~~~~
# Circles Staging Values
# ~~~~~~~~~~~~~~~~~~~~~~
# Main host
host: staging.circles.garden

# circles-api Service
# ~~~~~~~~~~~~~~~~~~~
apiService:
  # Docker image tag
  imageTag: v1.8.1

  # Ingress
  host: api.staging.circles.garden

  # Timeout in ms
  transferStepsTimeout: 150000

# circles-relayer Service
# ~~~~~~~~~~~~~~~~~~~~~~~
relayerService:
  # Docker image tag
  imageTag: v5.0.3-gb4bd66a

  # Ingress
  host: relay.staging.circles.garden

# AWS S3 Configuration
# ~~~~~~~~~~~~~~~~~~~~
aws:
  # Bucket for user content storage (via api)
  bucketUserContent: circles-ubi-staging

  # Bucket for trust edges file storage (via api-worker)
  bucketTrustNetwork: circles-ubi-network-staging

# "The Graph" Configuration
# ~~~~~~~~~~~~~~~~~~~~~~~~~
graph:
  # Graph node URL
  endpoint: https://graph.testing.circles.garden

  # Circles subgraph name
  subgraph: circlesubi/circles-ubi-stg

# Smart Contract Addresses
# ~~~~~~~~~~~~~~~~~~~~~~~~
contracts:
  hubAddress: 0xdbF22D4e8962Db3b2F1d9Ff55be728A887e47710
  proxyFactoryAddressCRC: 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2
  safeAddressCRC: 0x3E5c63644E683549055b9Be8653de26E0B4CD36E
  proxyFactoryAddress: 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2
  safeAddress130: 0x3E5c63644E683549055b9Be8653de26E0B4CD36E 
  safeAddress: 0x3E5c63644E683549055b9Be8653de26E0B4CD36E
  fallBackAddress: 0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4

# Relayer Addresses
# ~~~~~~~~~~~~~~~~~
relayer:
  funderAddress: 0x691b74E59b7D65572DFF5543e5A0e23c2F32049a
  senderAddress: 0x3454d8C54c94fAb51A3BedE50826F4C3d5445A79
