# ~~~~~~~~~~~~~~~~~~~~~~~~~
# Circles Production Values
# ~~~~~~~~~~~~~~~~~~~~~~~~~
# Main host
host: circles.garden

# circles-api Service
# ~~~~~~~~~~~~~~~~~~~
apiService:
  # Docker tag
  imageTag: v1.7.0-3-g128a6a7

  # Ingress
  host: api.circles.garden

# circles-relayer Service
# ~~~~~~~~~~~~~~~~~~~~~~~
relayerService:
  # Docker tag
  imageTag: v4.1.15-pre-cd8d524
  # Ingress
  host: relay.circles.garden

# AWS S3 Configuration
# ~~~~~~~~~~~~~~~~~~~~
aws:
  # Bucket for user content storage (via api)
  bucketUserContent: circles-ubi

  # Bucket for trust edges file storage (via api-worker)
  bucketTrustNetwork: circles-ubi-network

# "The Graph" Configuration
# ~~~~~~~~~~~~~~~~~~~~~~~~~
graph:
  # Graph node URL
  endpoint: https://graph.provisioning.circles.garden
  # Circles subgraph name
  subgraph: circlesubi/circles-ubi

# Smart Contract Addresses
# ~~~~~~~~~~~~~~~~~~~~~~~~
contracts:
  hubAddress: 0x29b9a7fBb8995b2423a71cC17cf9810798F6C543
  safeAddressCRC: 0x2CB0ebc503dE87CFD8f0eCEED8197bF7850184ae
  proxyFactoryAddressCRC: 0x8b4404DE0CaECE4b966a9959f134f0eFDa636156
  proxyFactoryAddress: 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2
  safeAddress: 0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552 
  fallBackAddress: 0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4

# Relayer Addresses
# ~~~~~~~~~~~~~~~~~
relayer:
  funderAddress: 0x450Fc3eAc8b847a759Cb05790cE7A1f465ac0cE8
  senderAddress: 0x9944Ce8e27CE1f16C4003f108b1C09e5Ae011bA0
