---
# task file
- name: Add helm repository
  kubernetes.core.helm_repository:
    name: cert-manager
    repo_url:  "https://charts.jetstack.io"


- name: Install certificate chart
  kubernetes.core.helm:
    update_repo_cache: true
    name: cert-manager
    namespace: cert-manager
    kubeconfig: "{{ k8s_kubeconfig }}"
    chart_version: v1.13.0
    chart_ref:  cert-manager/cert-manager
    create_namespace: true
    values:
      installCRDs: true
