---
# task file
- name: Add helm repository
  kubernetes.core.helm_repository:
    name: cert-manager
    repo_url:  "https://charts.jetstack.io"


- name: Install certificate chart
  kubernetes.core.helm:
    update_repo_cache: true
    name: cert-manager
    namespace: cert-manager
    kubeconfig: "{{ k8s_kubeconfig }}"
    chart_version: v1.18.2
    chart_ref:  cert-manager/cert-manager
    create_namespace: true
    values:
      installCRDs: true

- name: Copy cluster issuer file to local
  ansible.builtin.copy:
    src: cluster-issuer.yaml
    dest: /etc/config-helm/
    owner: root
    group: root
    mode: '0644'

- name: install cluster issuer
  kubernetes.core.k8s:
    apply: true
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: present
    src: /etc/config-helm/cluster-issuer.yaml