---
# task file

# - name: Install cert-manager
#   include_tasks: cert_manager.yml
- name: Add helm repository
  kubernetes.core.helm_repository:
    name: circles-graph-helm-charts
    repo_url: https://circlesubi.github.io/circles-helm/

- name: Ensures graph-protocol  dir exists
  file:
    path: /etc/config-helm/graph-protocol/
    state: directory
    mode: '0644'


- name: Copy values file depending on the env
  ansible.builtin.copy:
    src: values-{{ env }}.yaml
    dest: /etc/config-helm/graph-protocol
    owner: root
    group: root
    mode: '0644'

- name: Install cert-manager
  include_tasks: cert_manager.yml

- name: Install chart for xdai or chiado depending on group_vars
  kubernetes.core.helm:
    name: "graph-protocol"
    namespace: "graph-{{ ethereum_network  }}"
    kubeconfig: "{{ k8s_kubeconfig }}"
    chart_version: "{{ graph_protocol_chart_version }}"
    chart_ref: cirles-helm/graph-protocol
    create_namespace: true
    values_files: /etc/config-helm/graph-protocol/values-{{ env }}.yaml

