---
# task file

- name: Install cert-manager
  include_tasks: cert_manager.yml

- name: Ensures graph-protocol dir exists
  file: 
    path: /etc/config-helm/graph-protocol/ 
    state: directory
    mode: '0644'

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: values-{{ env }}.yaml
    dest: /etc/config-helm/graph-protocol
    owner: root
    group: root
    mode: '0644'


# workaround to install chart locally. Ideally we would have a repo in github with our charts
- name: Copy chart to remote to install
  ansible.builtin.copy:
    src: "{{ graph_protocol_chart_path }}"
    dest: /etc/config-helm/charts/
    owner: root
    group: root
    mode: '0644'
    

- name: Install chart for xdai or chiado depending on group_vars
  kubernetes.core.helm:
    name: "graph-protocol"
    namespace: "graph"
    kubeconfig: "{{ k8s_kubeconfig }}"
    chart_version: "{{ graph_protocol_chart_version }}"
    chart_ref: /etc/config-helm/charts/circles-graphprotocol/
    create_namespace: true
    values_files:
      - /etc/config-helm/charts/circles-graphprotocol/values.yaml
      - /etc/config-helm/charts/circles-graphprotocol/values-{{ env }}.yaml
    
