
# graph-protocol configuration
graphProtocol:
  logs: debug
  admin:
    name: index-node 
    port: 8020
  ipfs:
    name: ipfs
    port: 5001
  queryNode: query-node
  indexNode: index-node

# image details
image:
  repository: graphprotocol/graph-node
  pullPolicy: IfNotPresent
  tag: v0.29.0
# container
container:
  ports:
    http: 8000
    ws: 8001
    jsonRpc: 8020
    indexNode: 8030
    metrics: 8040

# services
service:
  http: 8000 # GraphQL RPC
  ws: 8001 # GraphQL WebSockets
  jsonRpc: 8020 # JSON RPC
  indexNode: 8030 # Subgraph indexing status
  metrics: 8040 # Prometheus metrics

# LetsEncrypt certificates
acmeEmail: circlesubi@gmail.com
acmeServer: https://acme-v02.api.letsencrypt.org/directory

