apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o circles-graph-node --volumes persistentVolumeClaim -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ipfs
  name: ipfs
  namespace: graph
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: ipfs
status:
  loadBalancer: {}
