apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ipfs-claim0
    namespace: graphtest
  name: ipfs-claim0
  namespace: graphtest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
status: {}
