apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-claim0
  name: postgres-claim0
  namespace: graph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
status: {}
