apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.graphProtocol.queryNode }}
  namespace: graphtest
spec:
  selector:
    matchLabels:
      app: {{ .Values.graphProtocol.queryNode }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.graphProtocol.queryNode }}
    spec:
      containers:
        - name: {{ .Values.graphProtocol.queryNode }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort:  {{ .Values.container.ports.http }}
            - name: ws
              containerPort: {{ .Values.container.ports.ws }}
            - name: index-node
              containerPort: {{ .Values.container.ports.indexNode }}
            - name: json-rpc
              containerPort: {{ .Values.container.ports.jsonRpc }}
            - name: metrics
              containerPort: {{ .Values.container.ports.metrics }}
          env:
            - name: GRAPH_LOG
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: GRAPH_LOG
            # Query nodes connect to Ethereum but don't call the Ethereum node
            # for anything; this argument could be made obsolete
            - name: ethereum
              valueFrom:
                configMapKeyRef:
                  name: ethereum-networks
                  key: networks         
            - name: ipfs
              valueFrom:
                configMapKeyRef:
                  key: IPFS
                  name: env
            - name: EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE
              value: synced 
            - name: DISABLE_BLOCK_INGESTOR
              value: "true"
            - name: GRAPH_LOG_QUERY_TIMING
              value: "gql" 
            - name: GRAPH_KILL_IF_UNRESPONSIVE
              value: "true"
            - name: postgres_host
              value: postgres
            - name: postgres_user
              value: graph-node
            - name: postgres_pass
              value: let-me-in
            - name: postgres_db
              value: graph-node
            - name: node_role
              value: {{ .Values.graphProtocol.queryNode }}
            - name: node_id
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources: {}
      restartPolicy: Always
status: {}
