apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    io.kompose.service: api
spec:
  ports:
    - name: "circles-api"
      port: {{.Values.api.port}}
      targetPort: {{.Values.api.port}}
  selector:
    io.kompose.service: api
