apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: api
  name: api-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: nfs
