apiVersion: v1
kind: ConfigMap
metadata:
  name: env
data:
  # AWS S3 Configuration
  # ~~~~~~~~~~~~~~~~~~~~
  AWS_REGION: {{.Values.aws.region}}
  AWS_S3_BUCKET: {{.Values.aws.bucketUserContent}}
  AWS_S3_BUCKET_TRUST_NETWORK: {{.Values.aws.bucketTrustNetwork}}

  # Redis service
  # ~~~~~~~~~~~~~
  REDIS_URL: redis://{{.Values.redisService.name}}:{{.Values.redisService.port}}

  # Service endpoints
  # ~~~~~~~~~~~~~~~~~
  API_SERVICE_ENDPOINT: http://{{.Values.apiService.name}}:{{.Values.apiService.port}}
  RELAY_SERVICE_ENDPOINT: http://{{.Values.relayerService.name}}-service:{{.Values.relayerService.port}}

  # "The Graph" Configuration
  # ~~~~~~~~~~~~~~~~~~~~~~~~~
  GRAPH_NODE_ENDPOINT: {{.Values.graph.endpoint}}
  SUBGRAPH_NAME: {{.Values.graph.subgraph}}

  # Smart Contract Addresses
  # ~~~~~~~~~~~~~~~~~~~~~~~~
  HUB_ADDRESS: {{.Values.contracts.hubAddress}}
  PROXY_FACTORY_ADDRESS: {{.Values.contracts.proxyFactoryAddress}}
  SAFE_ADDRESS: {{.Values.contracts.safeAddress}}
  PROXY_FACTORY_ADDRESS_CRC: {{.Values.contracts.proxyFactoryAddressCRC}}
  SAFE_CONTRACT_ADDRESS_CRC: {{.Values.contracts.safeAddressCRC}}
  SAFE_CONTRACT_ADDRESS_130: {{.Values.contracts.safeAddress130}}
  SAFE_DEFAULT_CALLBACK_HANDLER: {{.Values.contracts.fallBackAddress}}

  # PostgreSQL Databases
  # ~~~~~~~~~~~~~~~~~~~~
  POSTGRES_DATABASE_API: api
  POSTGRES_DATABASE_RELAYER: relayer

  # Indexed Data Configuration
  # ~~~~~~~~~~~~~~~~~~~~
  DATABASE_SOURCE: graph

  # Relayer Addresses
  # ~~~~~~~~~~~~~~~~~
  SAFE_FUNDER_ADDRESS: {{.Values.relayer.funderAddress}}
  SAFE_TX_ADDRESS: {{.Values.relayer.senderAddress}}

  # Relayer Configuration
  # ~~~~~~~~~~~~~~~~~~~~~
  ALLOWED_HOSTS: {{.Values.relayerService.host}}
  CELERY_BROKER_URL: redis://{{.Values.redisService.name}}:{{.Values.redisService.port}}/0
  CORS_ALLOWED_ORIGINS: https://{{.Values.host}},https://{{.Values.apiService.host}},https://{{.Values.relayerService.host}},https://dashboard.{{.Values.host}},https://preview.{{.Values.host}},{{.Values.circlesPinkURLs}},https://old.{{.Values.host}},https://devpreview.{{.Values.host}}
  DJANGO_ALLOWED_HOSTS: .{{.Values.host}}
  DJANGO_SETTINGS_MODULE: config.settings.production
  RELAYER_REDIS_URL: redis://{{.Values.redisService.name}}:{{.Values.redisService.port}}/0
