apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: circles-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-live
spec:
  tls:
    - hosts:
        - {{.Values.apiService.host}}
        - {{.Values.relayerService.host}}
      secretName: circles-tls
  rules:
    - host: {{.Values.apiService.host}}
      http:
        paths:
          - backend:
              serviceName: api
              servicePort: {{.Values.apiService.port}}
    - host: {{.Values.relayerService.host}}
      http:
        paths:
          - backend:
              serviceName: relayer-service
              servicePort: {{.Values.relayerService.port}}
