apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: circles-ingress-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "200"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{.Values.apiService.host}}
      secretName: circles-tls-api
  rules:
  - host: {{.Values.apiService.host}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.apiService.name}}
            port:
              number: {{.Values.apiService.port}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: circles-ingress-relayer
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{.Values.relayerService.host}}
      secretName: circles-tls-relayer
  rules:
  - host: {{.Values.relayerService.host}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.relayerService.name}}-service
            port:
              number: {{.Values.relayerService.port}}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: circles-ingress-payment-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{.Values.apiPaymentService.host}}
      secretName: circles-tls-payment-api
  rules:
  - host: {{.Values.apiPaymentService.host}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.apiPaymentService.name}}
            port:
              number: {{.Values.apiPaymentService.port}}
