apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o circles-infra-suite 
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ipfs
  name: ipfs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ipfs 
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o circles-infra-suite 
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: ipfs
    spec:
      containers:
        - image: ipfs/go-ipfs:v0.4.23
          name: ipfs
          ports:
            - containerPort: 5001
          resources: {}
          volumeMounts:
            - mountPath: /data/ipfs
              name: ipfs
      restartPolicy: Always
      volumes:
        - name: ipfs
          persistentVolumeClaim:
            claimName: ipfs
status: {}
