apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-live
spec:
  acme:
    email: {{.Values.acmeEmail}}
    server: {{.Values.acmeServer}}
    privateKeySecretRef:
      name: letsencrypt-live-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
