apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{.Values.redisService.name}}
  name: {{.Values.redisService.name}}
spec:
  ports:
    - name: tcp
      port: {{.Values.redisService.port}}
      targetPort: {{.Values.redisService.port}}
  selector:
    io.kompose.service: {{.Values.redisService.name}}
status:
  loadBalancer: {}
