apiVersion: v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      labels:
        io.kompose.service: redis
    spec:
      restartPolicy: Always
      containers:
        - name: circles-redis
          image: redis:6.0.1-alpine
          ports:
            - containerPort: {{.Values.redis.port}}
