apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - name: circles-redis
      port: {{.Values.redis.port}}
      targetPort: {{.Values.redis.port}}
  selector:
    io.kompose.service: redis
