apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o circles-infra-suite --volumes hostPath -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: relayer-scheduler
  name: relayer-scheduler
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    io.kompose.service: relayer-scheduler
status:
  loadBalancer: {}
