apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{.Values.relayerService.name}}
  name: {{.Values.relayerService.name}}
spec:
  ports:
    - name: http
      port: {{.Values.relayerService.port}}
      targetPort: {{.Values.relayerService.port}}
  selector:
    io.kompose.service: {{.Values.relayerService.name}}
status:
  loadBalancer: {}
