apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: relayer-service
  name: relayer-service
spec:
  ports:
    - name: circles-relayer-service
      port: {{.Values.relayerService.port}}
      targetPort: {{.Values.relayerService.port}}
  selector:
    io.kompose.service: relayer-service
