---
# task file for helm
- name: Add apt signing key for helm 
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add helm repository into sources list
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present 

- name: Install helm
  apt: 
   name: helm

