image:
  repository: sigp/lighthouse
  tag: v4.6.0
  pullPolicy: IfNotPresent

mode: "beacon"

checkpointSync:
  enabled: true
  url: "https://checkpoint.gnosischain.com/"

jwt:

defaultBeaconCommandTemplate: |
  - sh
  - -ac
  - >
    exec lighthouse
    beacon_node
    --network=gnosis
    --execution-endpoint=http://gnosis-nethermind.gnosis:8551
    --datadir=/data
    --disable-upnp
    --listen-address=0.0.0.0
    --port={{ include "lighthouse.p2pPort" . }}
    --discovery-port={{ include "lighthouse.p2pPort" . }}
    --http
    --http-address=0.0.0.0
    --http-port={{ .Values.httpPort }}
    --execution-jwt=/data/jwt.hex
    --metrics
    --metrics-address=0.0.0.0
    --metrics-port={{ .Values.metricsPort }}
  {{- if .Values.checkpointSync.enabled }}
    --checkpoint-sync-url={{ tpl .Values.checkpointSync.url $ }}
  {{- end }}
