
# -- Number of replicas
replicas: 1

image:
  # -- Lighthouse container image repository
  repository: sigp/lighthouse
  # -- Lighthouse container image tag
  tag: v4.2.0
  # -- Lighthouse container pull policy
  pullPolicy: IfNotPresent

# -- Mode can be 'beacon','validator' or 'bootnode'
mode: "beacon"

# -- Extra args for the lighthouse container
extraArgs:
  - --network=gnosis
  - --execution-endpoint=http://xdai-nethermind.xdai:8551
  - --checkpoint-sync-url=https://checkpoint.gnosischain.com/

jwt:
