image:
  repository: nethermind/nethermind
  tag: 1.25.4
  pullPolicy: IfNotPresent

extraArgs:
  - --config gnosis
  - --Init.MemoryHint 1500000000
  - --HealthChecks.Enabled true
  - --Network.MaxActivePeers 50
  - --Init.DiscoveryEnabled true
  - --Merge.Enabled true

jwt:

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: xdai-authentication@kubernetescrd
  hosts:
    - host: xdainode.infra.circles.garden
      paths:
      - path: /
        pathType: Prefix
      pathType: Prefix
  tls:
   - secretName: tls-xdainode
     hosts:
       - xdainode.infra.circles.garden
