image:
  repository: nethermind/nethermind
  tag: 1.25.4
  pullPolicy: IfNotPresent

extraArgs:
  - --config gnosis
  - --Init.MemoryHint 1500000000
  - --HealthChecks.Enabled true
  - --Network.MaxActivePeers 50
  - --Init.DiscoveryEnabled true
  - --Merge.Enabled true

jwt: 5067325748bcd5fb3dffe51169300ce05c28ff44a691f2dbdc9afc907143c1b2

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: xdai-authentication@kubernetescrd
  hosts:
    - host: xdainode.infra.circles.garden
      paths:
      - path: /
        pathType: Prefix
      pathType: Prefix
  tls:
   - secretName: tls-xdainode
     hosts:
       - xdainode.infra.circles.garden

persistence:
  # -- Uses an EmptyDir when not enabled
  enabled: true
  # -- Use an existing PVC when persistence.enabled
  existingClaim: nethermind-pvc
  # -- Access mode for the volume claim template
  accessModes:
  - ReadWriteOnce
  # -- Requested size for volume claim template
  size: 500Gi
  # -- Use a specific storage class
  # E.g 'local-path' for local storage to achieve best performance
  # Read more (https://github.com/rancher/local-path-provisioner)
  storageClassName: 'local-path'
  # -- Annotations for volume claim template
  annotations: {}
  # -- Selector for volume claim template
  selector: {}
  #   matchLabels:
  #     app.kubernetes.io/name: something