Vagrant.configure("2") do |config|
    #
    # Run Ansible from the Vagrant Host
    #
    config.vm.box = "debian/bullseye64"
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
      # ansible.verbose = "vvv"
    end
    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 8
    end
  end
  