---
# task file to run ad-hoc installations of resources not included in helm installation
- name: Install pre-requisites to run k8s
  pip:
    name:
      - kubernetes

- name: Set secret digest authentication
  kubernetes.core.k8s:
    state: present
    apply: true
    kubeconfig: "{{ k8s_kubeconfig }}"
    namespace: "{{ ethereum_network }}"
    template:
      - path: 'templates/set_secret_authentication.j2'

- name: Middleware to enable digest authentication
  kubernetes.core.k8s:
    state: present
    apply: true
    kubeconfig: "{{ k8s_kubeconfig }}"
    namespace: "{{ ethereum_network }}"
    template:
      - path: 'templates/digest_authentication_middleware.j2'



- name: Copy values file depending on the env
  ansible.builtin.copy:
    src: nethermind-pvc.yaml
    dest: /etc/config-helm/nethermind/nethermind-pvc.yaml
    owner: root
    group: root
    mode: '0644'
  tags: [rpc]

- name: Create PVC
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
    namespace: "{{ ethereum_network }}"
    src: /etc/config-helm/nethermind/nethermind-pvc.yaml
  tags: [rpc]