---
# task file to run ad-hoc installations of resources not included in helm installation
- name: Install pre-requisites to run k8s
  apt:
    name: python3-kubernetes
    state: present
  become: yes

- name: Set secret digest authentication
  kubernetes.core.k8s:
    state: present
    apply: true
    kubeconfig: "{{ k8s_kubeconfig }}"
    namespace: "{{ ethereum_network }}"
    template:
      - path: 'templates/set_secret_authentication.j2'

- name: Middleware to enable digest authentication
  kubernetes.core.k8s:
    state: present
    apply: true
    kubeconfig: "{{ k8s_kubeconfig }}"
    namespace: "{{ ethereum_network }}"
    template:
      - path: 'templates/digest_authentication_middleware.j2'
